[project]
name = "lx-music-api-server"
version = "2.0.2"
description = "LX Music Api Server修改版本"
authors = [
    {name = "ikun0014",email = "ikun0014@qq.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ujson (>=5.10.0,<6.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "logzero (>=1.7.0,<2.0.0)",
    "pycryptodome (>=3.22.0,<4.0.0)",
    "xmltodict (>=0.14.2,<0.15.0)",
    "redis (>=5.2.1,<6.0.0)",
    "aiohttp (>=3.11.18,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "pymysql (>=1.1.1,<2.0.0)",
    "cryptography (>=44.0.3,<45.0.0)",
    "dbutils (>=3.1.0,<4.0.0)",
    "aioquic (>=1.2.0,<2.0.0)",
    "uvicorn (>=0.34.2,<0.35.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "mirrors"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "primary"

